name: "Connect to an AWS role from a GitHub repository"

on:
  push:
    branches-ignore:
      - '*'
  pull_request:
    branches-ignore:
      - '*'

env:
  
  AWS_REGION : "eu-west-3" 

# Permission can be added at job level or workflow level    
permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout
jobs:
my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::381163360185:role/boutheyna_github_actions_role 
          role-session-name: Bouth_Session_Github_Actions
          aws-region: ${{ env.AWS_REGION }}

      
  