name: "Connect to an AWS role from a GitHub repository"

on:
  push:
    branches:
      - '*'
  

env:
  AWS_REGION: eu-west-3

jobs:
  AssumeRoleAndCallIdentity:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: "arn:aws:iam::381163360185:role/boutheyna_github_actions_role"
          role-session-name: GitHub_to_AWS_via_Boutheyna_OIDC
          aws-region: eu-west-3
      - name: Sts GetCallerIdentity
        run: |
          aws sts get-caller-identity