name: Connect to an AWS role from a GitHub repository

on:
  push:
    branches:
      - '*'
  
env:
  AWS_REGION: eu-west-3

permissions:
  id-token: write
  contents: read

jobs:
  AssumeRoleAndCallIdentity:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::381163360185:role/oidc_role_github
          role-session-name: testAssumeRole
          aws-region: eu-west-3

      - name: Sts GetCallerIdentity
        run: 
          aws sts get-caller-identity

  deploy-infra:
    needs: AssumeRoleAndCallIdentity
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v2
      
      # Initialize Terraform
      - name: 'Terraform Initialize'
        uses: hashicorp/setup-terraform@v1
        run: terraform init -reconfigure
        # run: terraform init
        with:
          backend-config: |
            bucket        = "$(AWS_BUCKET_NAME)"
            key           = "$(AWS_BUCKET_KEY_NAME)"
            region        = "eu-west-3"
          
      # Run Terraform commande

      - name: 'Terraform Plan'
        run: terraform plan

      - name: 'Terraform Apply'
        run: terraform apply -auto-approve